create database SQL29042020
GO

USE SQL29042020
GO

CREATE TABLE THONGTIN (
	MATK NVARCHAR (255) NOT NULL ,
	MATKHAU NVARCHAR (255),
	TENNV NVARCHAR (255),
	EMAIL NVARCHAR (255),
	CONSTRAINT FK_THONGTIN PRIMARY KEY (MATK)
)
GO
CREATE TABLE TRANGBI (
	MATB NVARCHAR (255) NOT NULL ,
	MU NVARCHAR (255),
	AO NVARCHAR (255),
	QUAN NVARCHAR (255),
	NHAN NVARCHAR(255),
	VUKHI NVARCHAR(255),
	THUCUOI NVARCHAR(255),
	TIEN FLOAT
	CONSTRAINT FK_TRANGBI PRIMARY KEY (MATB)
)
GO
CREATE TABLE MONPHAI (
	MAMP NVARCHAR (255) NOT NULL ,
	TENMONPHAI NVARCHAR (255),
	CHISOSUCMANH NVARCHAR(255),
	CONSTRAINT FK_MONPHAI PRIMARY KEY (MAMP)
)
GO
CREATE TABLE TUYETHOC (
	MATH NVARCHAR (255) NOT NULL ,
	TENTUYETHOC NVARCHAR (255),
	CONSTRAINT FK_TUYETHOC PRIMARY KEY (MATH)
)
GO
CREATE TABLE THANTHE (
	MATT NVARCHAR (255) NOT NULL ,
	CAPDO INT ,
	MAU FLOAT,
	NOILUC FLOAT,
	CONG FLOAT ,
	THU FLOAT,
	CHIMANG FLOAT,
	NETRANH FLOAT ,
	CONSTRAINT FK_THANTHE PRIMARY KEY (MATT)
)
GO

ALTER TABLE TUYETHOC ADD MAMP NVARCHAR (255)
ALTER TABLE TUYETHOC ADD CONSTRAINT FK_TUYETHOC_MONPHAI FOREIGN KEY (MAMP) REFERENCES MONPHAI(MAMP)

ALTER TABLE MONPHAI ADD MATK NVARCHAR (255)
ALTER TABLE THANTHE ADD MATK NVARCHAR (255)
ALTER TABLE TRANGBI ADD MATK NVARCHAR (255)


ALTER TABLE MONPHAI ADD CONSTRAINT FK_MONPHAI_THONGTIN FOREIGN KEY (MATK) REFERENCES THONGTIN(MATK)
ALTER TABLE THANTHE ADD CONSTRAINT FK_THANTHE_THONGTIN  FOREIGN KEY (MATK) REFERENCES THONGTIN(MATK)
ALTER TABLE TRANGBI ADD CONSTRAINT FK_TRANGBI_THONGTIN  FOREIGN KEY (MATK) REFERENCES THONGTIN(MATK)


INSERT INTO THONGTIN (MATK,MATKHAU,TENNV,EMAIL) VALUES ('BD101',123,'QZKMB','QZ258@GMAIL.COM')
INSERT INTO THONGTIN (MATK,MATKHAU,TENNV,EMAIL) VALUES ('BD102',123,'QWERT','QWERT@GMAIL.COM')
INSERT INTO THONGTIN (MATK,MATKHAU,TENNV,EMAIL) VALUES ('BD103',123,'RD','RD258@GMAIL.COM')
INSERT INTO THONGTIN (MATK,MATKHAU,TENNV,EMAIL) VALUES ('BD104',123,'BM','BM258@GMAIL.COM')
INSERT INTO THONGTIN (MATK,MATKHAU,TENNV,EMAIL) VALUES ('BD105',123,'WL','WL258@GMAIL.COM')
INSERT INTO THONGTIN (MATK,MATKHAU,TENNV,EMAIL) VALUES ('BD106',123,'KHÁNH',NULL)
INSERT INTO THONGTIN (MATK,MATKHAU,TENNV,EMAIL) VALUES ('BD107',123,'ĐỨC',NULL)



INSERT INTO MONPHAI (MAMP,TENMONPHAI,CHISOSUCMANH,MATK) VALUES ('NM','THIẾU LÂM','SỨC MẠNH:215,PHÒNG THỦ:150','BD102')
INSERT INTO MONPHAI (MAMP,TENMONPHAI,CHISOSUCMANH,MATK) VALUES ('NM','NGA MY','SỨC MẠNH:115,PHÒNG THỦ:179','BD104')
INSERT INTO MONPHAI (MAMP,TENMONPHAI,CHISOSUCMANH,MATK) VALUES ('TD','Tiêu Dao','SỨC MẠNH:230,PHÒNG THỦ:100','BD106')


INSERT INTO TUYETHOC (MATH,TENTUYETHOC,MAMP) VALUES ('TL01',N'LA HÁN THẬP BÁC CHƯỞNG','TL')
INSERT INTO TUYETHOC (MATH,TENTUYETHOC,MAMP) VALUES ('MN01',N'THANH TÂM PHỔ NIỆM CHÚ','NM')
INSERT INTO TUYETHOC (MATH,TENTUYETHOC,MAMP) VALUES ('TD01',N'MÉO NHỚ','TD')


INSERT INTO TRANGBI (MATB,MU,AO,QUAN,NHAN,VUKHI,THUCUOI,TIEN,MATK) VALUES ('TL001',NULL,NULL,NULL,NULL,NULL,NULL,5000,'BD101')
INSERT INTO TRANGBI (MATB,MU,AO,QUAN,NHAN,VUKHI,THUCUOI,TIEN,MATK) VALUES ('NM001',NULL,NULL,NULL,NULL,NULL,NULL,6000,'BD102')
INSERT INTO TRANGBI (MATB,MU,AO,QUAN,NHAN,VUKHI,THUCUOI,TIEN,MATK) VALUES ('TL002',NULL,NULL,NULL,NULL,NULL,NULL,5600,'BD103')
INSERT INTO TRANGBI (MATB,MU,AO,QUAN,NHAN,VUKHI,THUCUOI,TIEN,MATK) VALUES ('TD001',NULL,NULL,NULL,NULL,NULL,NULL,8000,'BD104')
INSERT INTO TRANGBI (MATB,MU,AO,QUAN,NHAN,VUKHI,THUCUOI,TIEN,MATK) VALUES ('TD002',NULL,NULL,NULL,NULL,NULL,NULL,5070,'BD105')
INSERT INTO TRANGBI (MATB,MU,AO,QUAN,NHAN,VUKHI,THUCUOI,TIEN,MATK) VALUES ('MN002',NULL,NULL,NULL,NULL,NULL,NULL,3070,'BD106')


SELECT * FROM  THONGTIN AS T
WHERE T.EMAIL = NULL

SELECT t.MATK , t.TENNV, MAX(TB.TIEN) FROM  THONGTIN AS T , TRANGBI AS TB
WHERE T.MATK = TB.MATK 
group by T.MATK = TB.MATK 

SELECT  COUNT(TT.MATH) AS SOLUONG FROM THONGTIN AS T, TRANGBI AS TB , MONPHAI AS MP , TUYETHOC AS TT
WHERE T.MATK = TB.MATK AND TB.TIEN >= 6000 AND MP.MAMP = TT.MAMP AND T.MATK = MP.MATK