CREATE DATABASE TULUYENSQL26042020
GO
USE  TULUYENSQL26042020
GO

CREATE TABLE CONGNHAN (
	MACN int  NOT NULL,
	HOTENCN NVARCHAR(255),
	GIOITINH NVARCHAR (15) ,
	NAMSINH date ,
	QUEQUAN NVARCHAR(255),
	SDT INT ,
	MAQL INT,
	CONSTRAINT FK_CONGNHAN PRIMARY KEY (MACN)
)
GO
CREATE TABLE QUANLY (
	MAQL INT  NOT NULL,
	HOTENQL NVARCHAR(255),
	GIOITINH NVARCHAR (15) ,
	SDT INT ,
	NGAYNHANCHUC date ,
	QUANLYSONGUOI INT ,
	CONSTRAINT FK_QUANLY PRIMARY KEY (MAQL)
)
GO
CREATE TABLE KHULAMVIEC (
	MAKLV INT  NOT NULL,
	TENKLV NVARCHAR(255),
	MAQL INT ,
	CONSTRAINT FK_KHULAMVIEC PRIMARY KEY (MAKLV)
)
GO

ALTER TABLE CONGNHAN ADD CONSTRAINT FK_CONGNHAN_QUANLY FOREIGN KEY(MAQL) REFERENCES QUANLY(MAQL)
ALTER TABLE KHULAMVIEC ADD CONSTRAINT FK_KHULAMVIEC_QUANLY FOREIGN KEY(MAQL) REFERENCES QUANLY(MAQL)

INSERT INTO CONGNHAN (MACN,HOTENCN,GIOITINH,NAMSINH,QUEQUAN,SDT,MAQL) VALUES (001,N'NGUYỄN VĂN A',N'NAM','1998-04-30',N'CỦ CHI',01234567,1);
INSERT INTO CONGNHAN (MACN,HOTENCN,GIOITINH,NAMSINH,QUEQUAN,SDT,MAQL) VALUES (002,N'NGUYỄN THỊ B',N'NỮ','19950730',N'ĐÀ LẠT',0386542342,1);
INSERT INTO CONGNHAN (MACN,HOTENCN,GIOITINH,NAMSINH,QUEQUAN,SDT,MAQL) VALUES (003,N'NGUYỄN VĂN C',N'BÊ ĐÊ','1993-06-30',N'VŨNG TÀU',0365264873,2);

INSERT INTO QUANLY (MAQL,HOTENQL,GIOITINH,SDT,NGAYNHANCHUC,QUANLYSONGUOI) VALUES (1,N'QUỲNH THỊ D', N'NỮ',0987653321,'2015-01-01',2);
INSERT INTO QUANLY (MAQL,HOTENQL,GIOITINH,SDT,NGAYNHANCHUC,QUANLYSONGUOI) VALUES (2,N'BÀNH VĂN E', N'NAM',0164373254,'2014-01-01',1);

INSERT INTO KHULAMVIEC (MAKLV,TENKLV,MAQL) VALUES (016,N'KHU KỸ THUẬT CÔNG NGHỆ',001);
INSERT INTO KHULAMVIEC (MAKLV,TENKLV,MAQL) VALUES (017,N'KHU VĂN PHÒNG',002);

SELECT * FROM QUANLY as Q , CONGNHAN AS C , KHULAMVIEC AS K