
--1 TRUY XUẤT THÔNG TIN BẢNG THAM GIA ĐỀ TÀI
SELECT * FROM THAMGIADT
--2 LẤY RA MÃ KHOA VÀ TÊN KHOA  TƯƠNG ỨNG
SELECT MAKHOA , TENKHOA FROM KHOA
--3 LẤY RA MÃ GV , TÊN GV VÀ HỌ TÊN NGƯỜI THÂN TƯƠNG ỨNG
SELECT GV.MAGV , GV.HOTEN ,NT.TEN FROM GIAOVIEN AS GV ,NGUOITHAN AS NT
--4 LẤY MÃ GV, TÊN GV, TÊN KHOA CỦA GIÁO VIÊN ĐÓ LÀM VIỆC 
SELECT GV.MAGV,GV.HOTEN ,K.TENKHOA FROM GIAOVIEN AS GV , BOMON AS BM , KHOA AS K
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA